apiVersion: v1
kind: Pod
metadata:
  name: ceph-mgr-1gzg3
  labels:
    app: pt
spec:
  hostNetwork: true
  hostPID: true
  hostIPC: true
  containers:
  - name: ceph-mgr-1gzg3
    image: ubuntu
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /host
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  #nodeName: k8s-control-plane-node # Force your pod to run on the control-plane node by uncommenting this line and changing to a control-plane node name
  volumes:
  - name: noderoot
    hostPath:
      path: /
